[tool.bumpversion]
commit = true
current_version = "1.67.1"
message = "Bump MSRV v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "rust-version = \"{current_version}\""
replace = "rust-version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = ".clippy.toml"
