# spell-checker: ignore dtolnay taiki Swatinem binstall taplo rustup

name: Deploy either-or-both
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish either-or-both
        run: cargo publish -p either-or-both --token ${{ secrets.CRATES_GITHUB_TOKEN }}
